namespace Red.Common.Client.Misc
{
    // Made from the FiveM Control List (https://docs.fivem.net/docs/game-references/controls/)
    public enum KeyboardKeys
    {
        Z = 20,
        V = 0,
        S = 8,
        D = 9,
        F = 23,
        C = 26,
        B = 29,
        W = 32,
        A = 34,
        Q = 44,
        R = 45,
        G = 47,
        H = 74,
        E = 38,
        M = 244,
        T = 245,
        Y = 246,
        N = 249,
        K = 311,
        PageUp = 10,
        PageDown = 11,
        LeftAlt = 19,
        LeftShift = 21,
        Spacebar = 22,
        LeftControl = 36,
        Tab = 37,
        OpenBracket = 39,
        ClosedBracket = 40,
        Period = 81,
        Comma = 82,
        Equals = 83,
        Minus = 84,
        X = 105,
        NumbPad6 = 107,
        NumbPad4 = 108,
        NumbPad5 = 110,
        NumbPad8 = 112,
        NumbPad7 = 117,
        NumbPad9 = 118,
        NumpadPlus = 314,
        NumpadMinus = 315,
        Insert = 121,
        CapsLock = 137,
        One = 157,
        Two = 158,
        Six = 159,
        Three = 160,
        Seven = 161,
        Eight = 162,
        Nine = 163,
        Four = 164,
        Five = 165,
        F1 = 288,
        F2 = 289,
        F5 = 166,
        F6 = 167,
        F7 = 168,
        F8 = 169,
        F3 = 170,
        F9 = 56,
        F10 = 57,
        ArrowUp = 172,
        ArrowDown = 173,
        ArrowLeft = 174,
        ArrowRight = 175,
        Delete = 178,
        L = 182,
        Enter = 191,
        P = 199,
        Escape = 200,
        Home = 212,
        Tilde = 243,
        ForwardSlash = 243,
        BackTick = 243,
    }
    // Made from the FiveM Control List (https://docs.fivem.net/docs/game-references/controls/) 
    public enum MouseInput
    {
        MouseRight = 1,
        MouseDown = 2,
        MouseWheelDown = 14,
        MouseWheelUp = 15,
        LeftMouseButton = 24,
        RightMouseButton = 25,
        ScrollWheelButton = 348
    }
    // Made from the FiveM Control List (https://docs.fivem.net/docs/game-references/controls/) 
    public enum ControllerButtons
    {
       PlayStationTriagle = 56,
       PlayStationSquare = 296,
       PlayStationCross = 298,
       PlayStationCircle = 225,
       PlayStationR1 = 90,
       PlayStationR2 = 129,
       PlayStationL1 = 185,
       PlayStationL2 = 207,
       PlayStationOptions = 318,
       PlayStationShare = 310,
       PlayStationDPadUp = 42,
       PlayStationDPadDown = 43,
       PlayStationDPadLeft = 47,
       PlayStationDPadRight = 46,
       PlayStationLeftStick = 28,
       PlayStationRightStick = 26,
       XboxY = 49,
       XboxX = 22,
       XboxA = 18,
       XboxB = 45,
       XboxBack = 0,
       XboxStart = 199,
       XboxRightButton = 69,
       XboxLeftButton = 89,
       XboxRightTrigger = 10,
       XboxLeftTrigger = 11,
       XboxLeftStick = 8,
       XboxRightStick = 12,
    }
    // Made from the FiveM Control List (https://docs.fivem.net/docs/game-references/controls/) 
    public enum ControlType
    {
        Player = 0,
        Unknown = 1,
        FrontEnd = 2
    }
    
    public enum OnScreenStatus
    {
        InActive = -1,
        Editing = 0,
        Finished = 1,
        Canceled = 2
    }

    public enum HUDIndex
    {
        HelpText = 0,
        FloatingHelpText1 = 1,
        FloatingHelpText2 = 2
    }

    public enum HUDIdentifier
    {
        HUD = 0,
        WantedStars = 1,
        WeaponIcon = 2,
        Cash = 3,
        MultiplayerCash = 4,
        MultiplayerMessage = 5,
        VehicleName = 6,
        AreaName = 7,
        VehicleClass = 8,
        StreetName = 9,
        HelpText = 10,
        FloatingHelpText1 = 11,
        FloatingHelpText2 = 12,
        CashChange = 13,
        Reticle = 14,
        SubtitleText = 15,
        RadioStation = 16,
        SavingGame = 17,
        GameStream = 18,
        WeaponWheel = 10,
        WeaponWheelStats = 20,
        Components = 21,
        Weapons = 22,
        MaxScriptedHUDComponents = 141
    }

    public enum IconType
    {
        ChatBox = 0,
        Email = 1,
        AddFriendRequest = 3,
        Nothing = 4,
        RightJumpingArrow = 7,
        RpIcon = 8,
        DollarIcon = 9
    }

    public enum NeonLights
    {
        Left = 0,
        Right = 1,
        Font = 2,
        Back = 3
    }

    public enum VehiclePaint
    {
        // CLASSIC | METALLIC
        Black = 0,
        Carbon_Black = 147,
        Graphite = 1,
        Anhracite_Black = 11,
        Black_Steel = 2,
        Dark_Steel = 3,
        Silver = 4,
        Bluish_Silver = 5,
        Rolled_Steel = 6,
        Shadow_Silver = 7,
        Stone_Silver = 8,
        Midnight_Silver = 9,
        Cast_Iron_Silver = 10,
        Red = 27,
        Torino_Red = 28,
        Formula_Red = 29,
        Lava_Red = 150,
        Blaze_Red = 30,
        Grace_Red = 31,
        Garnet_Red = 32,
        Sunset_Red = 33,
        Cabernet_Red = 34,
        Wine_Red = 143,
        Candy_Red = 35,
        Hot_Pink = 135,
        Pfister_Pink = 137,
        Salmon_Pink = 136,
        Sunrise_Orange = 36,
        Orange = 38,
        Bright_Orange = 138,
        Gold = 37,
        Bronze = 90,
        Yellow = 88,
        Race_Yellow = 89,
        Dew_Yellow = 91,
        Green = 139,
        Dark_Green = 49,
        Racing_Green = 50,
        Sea_Green = 51,
        Olive_Green = 52,
        Bright_Green = 53,
        Gasoline_Green = 54,
        Lime_Green = 92,
        Hunter_Green = 144,
        Securiror_Green = 125,
        Midnight_Blue = 141,
        Galaxy_Blue = 61,
        Dark_Blue = 62,
        Saxon_Blue = 63,
        Blue = 64,
        Bright_Blue = 140,
        Mariner_Blue = 65,
        Harbor_Blue = 66,
        Diamond_Blue = 67,
        Surf_Blue = 68,
        Nautical_Blue = 69,
        Racing_Blue = 73,
        Ultra_Blue = 70,
        Light_Blue = 74,
        Police_Car_Blue = 127,
        Epsilon_Blue = 157,
        Chocolate_Brown = 96,
        Bison_Brown = 101,
        Creek_Brown = 95,
        Feltzer_Brown = 94,
        Maple_Brown = 97,
        Beechwood_Brown = 103,
        Sienna_Brown = 104,
        Saddle_Brown = 98,
        Moss_Brown = 100,
        Woodbeech_Brown = 102,
        Straw_Brown = 99,
        Sandy_Brown = 105,
        Bleached_Brown = 106,
        Schafter_Purple = 71,
        Spinnaker_Purple = 72,
        Midnight_Purple = 142,
        Metallic_Midnight_Purple = 146,
        Bright_Purple = 145,
        Cream = 107,
        Ice_White = 111,
        Frost_White = 112,
        Pure_White = 134,
        Default_Alloy = 156,
        Champagne = 93,

        // Matte
        Matte_Black = 12,
        Matte_Gray = 13,
        Matte_Light_Gray = 14,
        Matte_Ice_White = 131,
        Matte_Blue = 83,
        Matte_Dark_Blue = 82,
        Matte_Midnight_Blue = 84,
        Matte_Midnight_Purple = 149,
        Matte_Schafter_Purple = 148,
        Matte_Red = 39,
        Matte_Dark_Red = 40,
        Matte_Orange = 41,
        Matte_Yellow = 42,
        Matte_Lime_Green = 55,
        Matte_Green = 128,
        Matte_Forest_Green = 151,
        Matte_Foliage_Green = 155,
        Matte_Brown = 129,
        Matte_Olive_Darb = 152,
        Matte_Dark_Earth = 153,
        Matte_Desert_Tan = 154,

        // Utiltity
        Util_Black = 15,
        Util_Black_Poly = 16,
        Util_Dark_Silver = 17,
        Util_Silver = 18,
        Util_Gun_Metal = 19,
        Util_Shadow_Silver = 20,
        Util_Red = 43,
        Util_Bright_Red = 44,
        Util_Garnet_Red = 45,
        Util_Dark_Green = 56,
        Util_Green = 57,
        Util_Dark_Blue = 75,
        Util_Midnight_Blue = 76,
        Util_Blue = 77,
        Util_Sea_Foam_Blue = 78,
        Util_Lightning_Blue = 79,
        Util_Maui_Blue_Poly = 80,
        Util_Bright_Blue = 81,
        Util_Brown = 108,
        Util_Medium_Brown = 109,
        Util_Light_Brown = 110,
        Util_Off_White = 122,

        // Worn
        Worn_Black = 21,
        Worn_Graphite = 22,
        Worn_Silver_Grey = 23,
        Worn_Silver = 24,
        Worn_Blue_Silver = 25,
        Worn_Shadow_Silver = 26,
        Worn_Red = 46,
        Worn_Golden_Red = 47,
        Worn_Dark_Red = 48,
        Worn_Dark_Green = 58,
        Worn_Green = 59,
        Worn_Sea_Wash = 60,
        Worn_Dark_Blue = 85,
        Worn_Blue = 86,
        Worn_Light_Blue = 87,
        Worn_Honey_Beige = 113,
        Worn_Brown = 114,
        Worn_Dark_Brown = 115,
        Worn_Straw_Beige = 116,
        Worn_Off_White = 121,
        Worn_Yellow = 123,
        Worn_Light_Orange = 124,
        Worn_Taxi_Yellow = 126,
        Worn_Orange = 130,
        Worn_White = 132,
        Worn_Olive_Army_Green = 133,

        // METALS
        Brushed_Steel = 117,
        Brushed_Black_Steel = 118,
        Brushed_Aluminum = 119,
        Pure_Gold = 158,
        Brushed_Gold = 159,
        Secret_Gold = 160,

        // CHROME
        Chrome = 120,
    }
}
